### ISSUE TITLE
have to refresh the page after you select a namespace

### ISSUE THREAD

**Issue by jeromedruais** [ibm-cloud-architecture/CSMO-ICP#2]
When you select ICP 2.1 Namespace in grafana's dashboard  (default for example), you have to refresh the page if you want to see graphs.
If you don't do that , $namespace still remains the same.
Once you select a namespace and refresh the page, title of the graph change with correct variable and the graph appears.

**Comment by RayStoner** [comment]
Hello Jerome, I have uploaded newer json files to the git hub page. Thanks for pointing this out - still not sure what happened. Follow up with dev. on that
