### ISSUE TITLE
Add etcd metrics to dashboards

### ISSUE THREAD

**Issue by hassenius** [ibm-cloud-architecture/CSMO-ICP#4]
Has anyone looked at the metrics available from etcd?
Seeing the central role of etcd, and the performance critical nature I think it's an important component to include in an operations dashboard.

Have a look at:
https://coreos.com/etcd/docs/latest/op-guide/monitoring.html
and
https://coreos.com/etcd/docs/latest/v2/metrics.html

**Comment by RayStoner** [comment]
I was actually reading that last week. Agree, just need some cycles.

**Comment by hassenius** [comment]
Seems at least in 2.1.0.3 there's a dashboard out-of-the-box at :/ grafana/dashboard/file/etcd-monitoring.json?orgId=1
So I guess don't have to worry anymore if the out-of-the-box one meets the requirements
